emgd/pvr: get it building with v3.4 kernel
Add emgd config option (DRM_EGD) and modify Makefiles for in-tree
builds.

rebased to v3.4 code

Fix build errors caused by changes to kernel interfaces introduced by
linux 3.2 such as:

error: 'THIS_MODULE' undeclared here (not in a function)

due to a missing THIS_MODULE definition which can be found in linux/export.h.

It also fixes a ream of errors like:

error: expected ')' before string constant

due to missing MODULE_PARM_DESC definition which can be found in
linux/moduleparam.h, included by linux/module.h, needed also for
MODULE_AUTHOR, etc.

variable name "pitch" from drm_framebuffer structure has changed
to "pitches" array in v3.4 kernel soruces.

avoid errors like these:
emgd_fbcon.c:128:28: error: 'struct drm_framebuffer' has no member named 'pitch'

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>